feat: 課程列表 page 功能
HSNM2/backend-nodejs pull request #15
Opened 2023-05-21 13:22 UTC by ankazu

page 設定，上限 20 筆資料

2023-05-21 14:37 UTC, paperhsiaooo requested changes

2023-05-21 14:37 UTC, paperhsiaooo commented on controllers/coursesController/index.js
> +      const courseData = await Course.findAndCountAll({
Limit 會是由前端送給後端
這樣當前端要改成單頁 10 筆時，後端也不用跟著動了
這部分可能再修正一下

2023-05-21 14:37 UTC, paperhsiaooo commented on controllers/coursesController/index.js
> +      console.log(courseData.rows)
console.log 記得要移除唷！

2023-05-22 02:26 UTC, ankazu reviewed
修改回覆

2023-05-22 02:26 UTC, ankazu commented on controllers/coursesController/index.js
> +      const courseData = await Course.findAndCountAll({
已修改

2023-05-22 02:26 UTC, ankazu commented on controllers/coursesController/index.js
> +      console.log(courseData.rows)
已移除

2023-05-22 03:08 UTC, paperhsiaooo approved these changes

2023-05-22 03:09 UTC, paperhsiaooo commented
@ankazu 感謝 John，再麻煩合併至 dev branch 🙏

2023-05-22 03:10 UTC, merged