購物車金流相關調整
HSNM2/backend-nodejs pull request #23
Opened 2023-06-08 13:57 UTC by ankazu

cart 取得課程相關資料與總價計算，重複使用程式，另設新檔。
金流混淆參數增加 Name
order 新增 name 參數、商品詳細上限50字元。
createOrder 修改訂單參數、取得課程總價

2023-06-08 14:36 UTC, paperhsiaooo requested changes

2023-06-08 14:36 UTC, paperhsiaooo commented on controllers/cartController/cartOperations.js
> +}
Controller 內部通常都放跟路由後續有關動作的 js
1. calculateTotalPrice 的 function 應放在 src 下的 js 或 utils 內，可能需找個適當的 js 放入

2023-06-08 14:36 UTC, paperhsiaooo commented on controllers/cartController/crypt.js
先前沒注意到 crypt.js 也應放在 src 下的 js 或者 utils 的資料夾下

2023-06-08 14:36 UTC, paperhsiaooo commented on controllers/cartController/index.js
> +const { getCourseData, calculateTotalPrice } = require('./cartOperations')
路徑需跟著 cartOperations 位置改變而更動

2023-06-08 14:36 UTC, paperhsiaooo commented
@ankazu 再麻煩修正了

2023-06-09 12:24 UTC, ankazu reviewed
檔案搬遷

2023-06-09 12:24 UTC, ankazu commented on controllers/cartController/cartOperations.js
> +}
新增 calculate.js

2023-06-09 12:25 UTC, ankazu commented on controllers/cartController/crypt.js
移至 utils 資料夾

2023-06-09 12:25 UTC, ankazu commented on controllers/cartController/index.js
> +const { getCourseData, calculateTotalPrice } = require('./cartOperations')
以調整

2023-06-09 12:49 UTC, paperhsiaooo approved these changes

2023-06-09 12:49 UTC, paperhsiaooo commented
@ankazu ok，再麻煩合併了🙏

2023-06-09 12:49 UTC, merged